-- V7: Create recipe schema + lookup tables (cuisines, sauce_usage_types, cooking_method_types) + seed

CREATE SCHEMA IF NOT EXISTS recipe;

-- cuisines: flat classification by country (+ fusion extra, no hierarchy)
CREATE TABLE IF NOT EXISTS recipe.cuisines (
    code    text PRIMARY KEY,   -- ISO 3166-1 alpha-2 for countries; ad-hoc codes for region/fusion
    name_ko text NOT NULL,
    name_ja text NOT NULL,
    name_en text NOT NULL
);

CREATE TABLE IF NOT EXISTS recipe.sauce_usage_types (
    code    text PRIMARY KEY,   -- 'dip','marinade','glaze','soup_base','stir_fry','braise','dressing'
    name_ko text NOT NULL,
    name_ja text NOT NULL,
    name_en text NOT NULL
);

CREATE TABLE IF NOT EXISTS recipe.cooking_method_types (
    code    text PRIMARY KEY,   -- 'grill','pan_fry','stir_fry','boil','simmer','steam','raw','air_fry'
    name_ko text NOT NULL,
    name_ja text NOT NULL,
    name_en text NOT NULL
);

-- Seed cuisines: countries (ISO 3166-1 alpha-2), one row per line
INSERT INTO recipe.cuisines (code, name_ko, name_ja, name_en) VALUES
    -- Asia
    ('KR','대한민국','韓国','South Korea'),
    ('KP','북한','北朝鮮','North Korea'),
    ('JP','일본','日本','Japan'),
    ('CN','중국','中国','China'),
    ('TW','대만','台湾','Taiwan'),
    ('HK','홍콩','香港','Hong Kong'),
    ('MO','마카오','マカオ','Macau'),
    ('MN','몽골','モンゴル','Mongolia'),
    ('VN','베트남','ベトナム','Vietnam'),
    ('TH','태국','タイ','Thailand'),
    ('LA','라오스','ラオス','Laos'),
    ('KH','캄보디아','カンボジア','Cambodia'),
    ('MM','미얀마','ミャンマー','Myanmar'),
    ('MY','말레이시아','マレーシア','Malaysia'),
    ('SG','싱가포르','シンガポール','Singapore'),
    ('ID','인도네시아','インドネシア','Indonesia'),
    ('PH','필리핀','フィリピン','Philippines'),
    ('BN','브루나이','ブルネイ','Brunei'),
    ('TL','동티모르','東ティモール','Timor-Leste'),
    ('IN','인도','インド','India'),
    ('PK','파키스탄','パキスタン','Pakistan'),
    ('BD','방글라데시','バングラデシュ','Bangladesh'),
    ('LK','스리랑카','スリランカ','Sri Lanka'),
    ('NP','네팔','ネパール','Nepal'),
    ('BT','부탄','ブータン','Bhutan'),
    ('MV','몰디브','モルディブ','Maldives'),
    ('AF','아프가니스탄','アフガニスタン','Afghanistan'),
    -- Central Asia
    ('KZ','카자흐스탄','カザフスタン','Kazakhstan'),
    ('UZ','우즈베키스탄','ウズベキスタン','Uzbekistan'),
    ('TM','투르크메니스탄','トルクメニスタン','Turkmenistan'),
    ('KG','키르기스스탄','キルギス','Kyrgyzstan'),
    ('TJ','타지키스탄','タジキスタン','Tajikistan'),
    -- Middle East
    ('IR','이란','イラン','Iran'),
    ('IQ','이라크','イラク','Iraq'),
    ('SY','시리아','シリア','Syria'),
    ('LB','레바논','レバノン','Lebanon'),
    ('JO','요르단','ヨルダン','Jordan'),
    ('IL','이스라엘','イスラエル','Israel'),
    ('PS','팔레스타인','パレスチナ','Palestine'),
    ('SA','사우디아라비아','サウジアラビア','Saudi Arabia'),
    ('YE','예멘','イエメン','Yemen'),
    ('OM','오만','オマーン','Oman'),
    ('AE','아랍에미리트','アラブ首長国連邦','United Arab Emirates'),
    ('QA','카타르','カタール','Qatar'),
    ('BH','바레인','バーレーン','Bahrain'),
    ('KW','쿠웨이트','クウェート','Kuwait'),
    ('TR','튀르키예','トルコ','Turkey'),
    ('CY','키프로스','キプロス','Cyprus'),
    ('GE','조지아','ジョージア','Georgia'),
    ('AM','아르메니아','アルメニア','Armenia'),
    ('AZ','아제르바이잔','アゼルバイジャン','Azerbaijan'),
    -- Europe
    ('GB','영국','イギリス','United Kingdom'),
    ('IE','아일랜드','アイルランド','Ireland'),
    ('FR','프랑스','フランス','France'),
    ('DE','독일','ドイツ','Germany'),
    ('IT','이탈리아','イタリア','Italy'),
    ('ES','스페인','スペイン','Spain'),
    ('PT','포르투갈','ポルトガル','Portugal'),
    ('NL','네덜란드','オランダ','Netherlands'),
    ('BE','벨기에','ベルギー','Belgium'),
    ('LU','룩셈부르크','ルクセンブルク','Luxembourg'),
    ('CH','스위스','スイス','Switzerland'),
    ('AT','오스트리아','オーストリア','Austria'),
    ('GR','그리스','ギリシャ','Greece'),
    ('SE','스웨덴','スウェーデン','Sweden'),
    ('NO','노르웨이','ノルウェー','Norway'),
    ('DK','덴마크','デンマーク','Denmark'),
    ('FI','핀란드','フィンランド','Finland'),
    ('IS','아이슬란드','アイスランド','Iceland'),
    ('PL','폴란드','ポーランド','Poland'),
    ('CZ','체코','チェコ','Czechia'),
    ('SK','슬로바키아','スロバキア','Slovakia'),
    ('HU','헝가리','ハンガリー','Hungary'),
    ('RO','루마니아','ルーマニア','Romania'),
    ('BG','불가리아','ブルガリア','Bulgaria'),
    ('HR','크로아티아','クロアチア','Croatia'),
    ('SI','슬로베니아','スロベニア','Slovenia'),
    ('RS','세르비아','セルビア','Serbia'),
    ('BA','보스니아 헤르체고비나','ボスニア・ヘルツェゴビナ','Bosnia and Herzegovina'),
    ('ME','몬테네그로','モンテネグロ','Montenegro'),
    ('MK','북마케도니아','北マケドニア','North Macedonia'),
    ('AL','알바니아','アルバニア','Albania'),
    ('XK','코소보','コソボ','Kosovo'),
    ('RU','러시아','ロシア','Russia'),
    ('UA','우크라이나','ウクライナ','Ukraine'),
    ('BY','벨라루스','ベラルーシ','Belarus'),
    ('MD','몰도바','モルドバ','Moldova'),
    ('LT','리투아니아','リトアニア','Lithuania'),
    ('LV','라트비아','ラトビア','Latvia'),
    ('EE','에스토니아','エストニア','Estonia'),
    ('MT','몰타','マルタ','Malta'),
    ('AD','안도라','アンドラ','Andorra'),
    ('MC','모나코','モナコ','Monaco'),
    ('SM','산마리노','サンマリノ','San Marino'),
    ('VA','바티칸','バチカン','Vatican City'),
    ('LI','리히텐슈타인','リヒテンシュタイン','Liechtenstein'),
    -- Africa
    ('EG','이집트','エジプト','Egypt'),
    ('LY','리비아','リビア','Libya'),
    ('TN','튀니지','チュニジア','Tunisia'),
    ('DZ','알제리','アルジェリア','Algeria'),
    ('MA','모로코','モロッコ','Morocco'),
    ('SD','수단','スーダン','Sudan'),
    ('SS','남수단','南スーダン','South Sudan'),
    ('ET','에티오피아','エチオピア','Ethiopia'),
    ('ER','에리트레아','エリトリア','Eritrea'),
    ('DJ','지부티','ジブチ','Djibouti'),
    ('SO','소말리아','ソマリア','Somalia'),
    ('KE','케냐','ケニア','Kenya'),
    ('UG','우간다','ウガンダ','Uganda'),
    ('TZ','탄자니아','タンザニア','Tanzania'),
    ('RW','르완다','ルワンダ','Rwanda'),
    ('BI','부룬디','ブルンジ','Burundi'),
    ('NG','나이지리아','ナイジェリア','Nigeria'),
    ('GH','가나','ガーナ','Ghana'),
    ('CI','코트디부아르','コートジボワール','Côte d''Ivoire'),
    ('SN','세네갈','セネガル','Senegal'),
    ('ML','말리','マリ','Mali'),
    ('BF','부르키나파소','ブルキナファソ','Burkina Faso'),
    ('NE','니제르','ニジェール','Niger'),
    ('TD','차드','チャド','Chad'),
    ('CM','카메룬','カメルーン','Cameroon'),
    ('CF','중앙아프리카공화국','中央アフリカ共和国','Central African Republic'),
    ('GA','가봉','ガボン','Gabon'),
    ('CG','콩고 공화국','コンゴ共和国','Republic of the Congo'),
    ('CD','콩고 민주 공화국','コンゴ民主共和国','DR Congo'),
    ('AO','앙골라','アンゴラ','Angola'),
    ('ZM','잠비아','ザンビア','Zambia'),
    ('ZW','짐바브웨','ジンバブエ','Zimbabwe'),
    ('MW','말라위','マラウイ','Malawi'),
    ('MZ','모잠비크','モザンビーク','Mozambique'),
    ('ZA','남아프리카공화국','南アフリカ','South Africa'),
    ('NA','나미비아','ナミビア','Namibia'),
    ('BW','보츠와나','ボツワナ','Botswana'),
    ('LS','레소토','レソト','Lesotho'),
    ('SZ','에스와티니','エスワティニ','Eswatini'),
    ('MG','마다가스카르','マダガスカル','Madagascar'),
    ('MU','모리셔스','モーリシャス','Mauritius'),
    ('SC','세이셸','セーシェル','Seychelles'),
    ('KM','코모로','コモロ','Comoros'),
    ('CV','카보베르데','カーボベルデ','Cabo Verde'),
    ('ST','상투메 프린시페','サントメ・プリンシペ','São Tomé and Príncipe'),
    ('GW','기니비사우','ギニアビサウ','Guinea-Bissau'),
    ('GN','기니','ギニア','Guinea'),
    ('SL','시에라리온','シエラレオネ','Sierra Leone'),
    ('LR','라이베리아','リベリア','Liberia'),
    ('TG','토고','トーゴ','Togo'),
    ('BJ','베냉','ベナン','Benin'),
    ('GM','감비아','ガンビア','Gambia'),
    ('MR','모리타니','モーリタニア','Mauritania'),
    ('GQ','적도기니','赤道ギニア','Equatorial Guinea'),
    -- Americas
    ('US','미국','アメリカ','United States'),
    ('CA','캐나다','カナダ','Canada'),
    ('MX','멕시코','メキシコ','Mexico'),
    ('GT','과테말라','グアテマラ','Guatemala'),
    ('BZ','벨리즈','ベリーズ','Belize'),
    ('SV','엘살바도르','エルサルバドル','El Salvador'),
    ('HN','온두라스','ホンジュラス','Honduras'),
    ('NI','니카라과','ニカラグア','Nicaragua'),
    ('CR','코스타리카','コスタリカ','Costa Rica'),
    ('PA','파나마','パナマ','Panama'),
    ('CU','쿠바','キューバ','Cuba'),
    ('JM','자메이카','ジャマイカ','Jamaica'),
    ('HT','아이티','ハイチ','Haiti'),
    ('DO','도미니카공화국','ドミニカ共和国','Dominican Republic'),
    ('BS','바하마','バハマ','Bahamas'),
    ('BB','바베이도스','バルバドス','Barbados'),
    ('TT','트리니다드 토바고','トリニダード・トバゴ','Trinidad and Tobago'),
    ('CO','콜롬비아','コロンビア','Colombia'),
    ('VE','베네수엘라','ベネズエラ','Venezuela'),
    ('GY','가이아나','ガイアナ','Guyana'),
    ('SR','수리남','スリナム','Suriname'),
    ('EC','에콰도르','エクアドル','Ecuador'),
    ('PE','페루','ペルー','Peru'),
    ('BR','브라질','ブラジル','Brazil'),
    ('BO','볼리비아','ボリビア','Bolivia'),
    ('PY','파라과이','パラグアイ','Paraguay'),
    ('UY','우루과이','ウルグアイ','Uruguay'),
    ('AR','아르헨티나','アルゼンチン','Argentina'),
    ('CL','칠레','チリ','Chile'),
    -- Oceania
    ('AU','호주','オーストラリア','Australia'),
    ('NZ','뉴질랜드','ニュージーランド','New Zealand'),
    ('PG','파푸아뉴기니','パプアニューギニア','Papua New Guinea'),
    ('FJ','피지','フィジー','Fiji'),
    ('SB','솔로몬제도','ソロモン諸島','Solomon Islands'),
    ('VU','바누아투','バヌアツ','Vanuatu'),
    ('WS','사모아','サモア','Samoa'),
    ('TO','통가','トンガ','Tonga'),
    ('KI','키리바시','キリバス','Kiribati'),
    ('FM','미크로네시아','ミクロネシア','Micronesia'),
    ('MH','마셜제도','マーシャル諸島','Marshall Islands'),
    ('PW','팔라우','パラオ','Palau'),
    ('NR','나우루','ナウル','Nauru'),
    ('TV','투발루','ツバル','Tuvalu')
ON CONFLICT DO NOTHING;

-- Seed cuisines: region / fusion extras (non-country, ad-hoc codes)
INSERT INTO recipe.cuisines (code, name_ko, name_ja, name_en) VALUES
    ('FUSION','퓨전','フュージョン','Fusion')
ON CONFLICT DO NOTHING;

-- Seed sauce_usage_types, one row per line
INSERT INTO recipe.sauce_usage_types (code, name_ko, name_ja, name_en) VALUES
    ('dip','찍어먹기','ディップ','Dip'),
    ('marinade','재움','マリネ','Marinade'),
    ('glaze','글레이즈','グレーズ','Glaze'),
    ('soup_base','국물 베이스','スープベース','Soup base'),
    ('stir_fry','볶음','炒め','Stir-fry'),
    ('braise','조림','煮込み','Braise'),
    ('dressing','드레싱','ドレッシング','Dressing')
ON CONFLICT DO NOTHING;

-- Seed cooking_method_types, one row per line
INSERT INTO recipe.cooking_method_types (code, name_ko, name_ja, name_en) VALUES
    ('grill','구이','グリル','Grill'),
    ('pan_fry','팬프라이','パン焼き','Pan-fry'),
    ('stir_fry','볶음','炒め','Stir-fry'),
    ('boil','삶기','茹で','Boil'),
    ('simmer','조림','煮込み','Simmer'),
    ('steam','찜','蒸し','Steam'),
    ('raw','생','生','Raw'),
    ('air_fry','에어프라이','エアフライ','Air-fry')
ON CONFLICT DO NOTHING;
